export const MANAGEMENT_PPE_SOURCE_UIDS = [
  "MEP:t10", "POS:t06", "POS:t08", "POS:t40", "POS:t41", "POS:t42", "POS:t43", "POS:t44",
];

export const MANAGEMENT_PPE_CATALOG = [
  {
    uid: "MGMT:t05",
    sourceUid: "MEP:t10",
    subsystem: "MANAGEMENT",
    level: "T",
    cat: "PPE",
    name: "Hi-visibility bump cap - baseball style anti-bump cap",
    brand: "Portwest",
    model: "PS59 AirTech Bump Cap",
    domain: "Management site visits / low-clearance areas",
    standard: "EN 812",
    statut: "OB",
    qty: 1,
    price: 18,
    period: "3 years or replace if damaged",
    desc: "Light head protection for management site visits and inspections in low-clearance plant rooms, under cable trays and inside technical-room areas. Not a substitute for an EN 397 helmet where falling-object risk exists.",
    productUrl: "https://www.portwest.com/products/view/PS59",
  },
  {
    uid: "MGMT:t06",
    sourceUid: "POS:t06",
    subsystem: "MANAGEMENT",
    level: "T",
    cat: "PPE",
    name: "Arc-flash Safety Glasses EN166",
    brand: "Bollé Safety",
    model: "Cobra COBPSI",
    domain: "All domains",
    standard: "EN 166 / EN 170",
    statut: "OB",
    qty: 1,
    price: 22,
    period: "1 year",
    desc: "Anti-scratch, anti-fog safety glasses for systematic use during all site visits and inspections.",
    productUrl: "https://www.bollesafety.com/fr/lunettes-de-securite/cobra",
  },
  {
    uid: "MGMT:t08",
    sourceUid: "POS:t08",
    subsystem: "MANAGEMENT",
    level: "T",
    cat: "PPE",
    name: "ATEX Headlamp – 115 lm",
    brand: "Peli",
    model: "2755Z0",
    domain: "All domains",
    standard: "ATEX Zone 0 – IP54",
    statut: "RC",
    qty: 1,
    price: 118,
    period: "3 years",
    desc: "Intrinsically safe headlamp for inspections in hazardous environments and confined spaces.",
    productUrl: "https://www.peli.com/es/en/product/flashlights/headlamp/2755z0/",
  },
  {
    uid: "MGMT:t40",
    sourceUid: "POS:t40",
    subsystem: "MANAGEMENT",
    level: "T",
    cat: "PPE",
    name: "Safety Shoes S3 ESD SRC mid-cut",
    brand: "PUMA Safety",
    model: "KRYPTON MID 634200",
    domain: "All domains",
    standard: "EN ISO 20345 – S3 ESD SRC",
    statut: "OB",
    qty: 1,
    price: 119.39,
    period: "2 years",
    desc: "Mid-cut safety footwear for site visits and depot access. Slip resistance and toe protection.",
    productUrl:
      "https://www.puma-safety.com/eu/de/maenner/schuhe/sicherheitsschuhe/sicherheitsschuhe-s3/231/krypton-mid-puma-safety-sicherheitsschuhe-s3-esd",
  },
  {
    uid: "MGMT:t41",
    sourceUid: "POS:t41",
    subsystem: "MANAGEMENT",
    level: "T",
    cat: "PPE",
    name: "Hi-visibility Vest Class 2",
    brand: "Seton",
    model: "CPS4375052",
    domain: "Platform work zones / worksite visibility",
    standard: "EN ISO 20471 Class 2",
    statut: "OB",
    qty: 1,
    price: 9.9,
    period: "2 years",
    desc: "Mandatory visibility PPE for platform-side activity and site inspections.",
    productUrl: "https://www.seton.fr/gilet-securite-haute-visibilite-2-ceintures.html",
  },
  {
    uid: "MGMT:t42",
    sourceUid: "POS:t42",
    subsystem: "MANAGEMENT",
    level: "T",
    cat: "PPE",
    name: "Hi-visibility Work Trousers Class 2",
    brand: "Portwest",
    model: "PW340",
    domain: "All domains",
    standard: "EN ISO 20471 Class 2",
    statut: "OB",
    qty: 1,
    price: 79,
    period: "2 years",
    desc: "Base hi-vis lower-body PPE for site visits, depot inspections and platform-side activity.",
    productUrl:
      "https://www.lyreco.com/webshop/FRCH/pantalon-haute-visibilite-portwest-pw340-classe-2-orange-noir-taille-58-product-000000000016482764.html",
  },
  {
    uid: "MGMT:t43",
    sourceUid: "POS:t43",
    subsystem: "MANAGEMENT",
    level: "T",
    cat: "PPE",
    name: "Hi-visibility Short-sleeve Work Polo Class 2",
    brand: "Portwest",
    model: "RT22",
    domain: "All domains",
    standard: "EN ISO 20471 Class 2",
    statut: "OB",
    qty: 1,
    price: 24,
    period: "1 year",
    desc: "High-visibility upper-body workwear for warmer periods and site inspections.",
    productUrl: "https://www.hiviskings.com/portwest-rt22-class-2-hi-vis-safety-polo-rt22",
  },
  {
    uid: "MGMT:t44",
    sourceUid: "POS:t44",
    subsystem: "MANAGEMENT",
    level: "T",
    cat: "PPE",
    name: "Hi-visibility Winter Bomber Jacket Class 3",
    brand: "Portwest",
    model: "C465",
    domain: "All domains – winter outdoor work",
    standard: "EN ISO 20471 Class 3 – EN 343",
    statut: "OB",
    qty: 1,
    price: 69,
    period: "3 years",
    desc: "Cold-weather high-visibility outer layer for winter site visits and outdoor inspections.",
    productUrl:
      "https://www.lyreco.com/webshop/FRLU/veste-bomber-hi-vis-portwest-c465-orange-bleu-marine-taille-m-la-piece-product-000000000007875167.html",
  },
];
